services:
  mongo-fallback:
    build:
      context: ./mongo
      dockerfile: Dockerfile
    container_name: mongo-fallback
    ports:
      - "27017:27017"
    volumes:
      - ./mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - backend

  springboot-app:
    build:
      context: ./app
      dockerfile: Dockerfile
      args:
        - MONGODB_URI=mongodb://mongo-fallback:27017/testdb
    container_name: springboot-app
    ports:
      - "8080:8080"  # host:container
    environment:
      # Spring Boot picks up this URI automatically
      SPRING_DATA_MONGODB_URI: mongodb://mongo-fallback:27017/testdb
    depends_on:
      - mongo-fallback
    healthcheck:
      test: ["CMD","curl","-f","http://localhost:8080/cache"]
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - backend

  react-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_BACKEND_URL=http://localhost:8080/cache
    image: myorg/react-frontend:latest
    ports:
      - "3000:80"        # host 3000 → container 80
    restart: unless-stopped
    depends_on: 
      - springboot-app
    networks:
      - backend

networks:
  backend:
    driver: bridge
