apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-tomcat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcat-app
  template:
    metadata:
      labels:
        app: tomcat-app
    spec:
      containers:
      - name: tomcat-app
        image: springboot-tomcat-app
        ports:
        - containerPort: 8080
        env:
          - name: SPRING_DATA_MONGODB_URI
            value: mongodb://mongo-service:27017/testdb

---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
spec:
  selector:
    app: tomcat-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
